name: "Test on push"

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cache npm dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('package.json') }}
          path: node_modules
      - name: install
        run: npm install
      - name: cache purescript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.yaml') }}
          path: |
            .spago
            output
      - name: bundle test code
        run: npm run test:build
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      - name: mocha tests
        run: npm run test:run

  # Automatically merge dependabot PRs if the tests pass and its not a major
  # version change.
  auto-merge:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'pull_request' && github.base_ref == 'master' && github.actor == 'dependabot[bot]'
    steps:
      - name: automerge dependabot PRs
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
